apiVersion: v2
name: java-api
description: Java 21 Spring Boot API workload
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://./charts/common
