fullnameOverride: ""
nameOverride: ""

enabled: true
replicas: 1

image:
  registry: atlas.azurecr.io
  name: atlas-catalog-api
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

health:
  readinessPath: /actuator/health/readiness
  livenessPath: /actuator/health/liveness

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

configmap:
  enabled: true

configurations:
  ROOT_LOG_LEVEL: INFO
